name: Develop Push Workflow

on:
  push:
    branches:
      - develop

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "Hello Push World!"

      - name: Print Goodbye
        run: echo "Done - Bye!"
