name: Test Direct Workflow 012

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "Hello Test Direct World!"

      - name: Print Goodbye
        run: echo "Done Test Direct - Bye!"
